<?php

$class_map = array(
    'premium-banner' => 'PremiumAddons\Widgets\Premium_Banner',
    'premium-blog' => 'PremiumAddons\Widgets\Premium_Blog',
    'premium-button' => 'PremiumAddons\Widgets\Premium_Button',
    'premium-carousel' => 'PremiumAddons\Widgets\Premium_Carousel',
    'premium-contactform' => 'PremiumAddons\Widgets\Premium_Contactform',
    'premium-countdown' => 'PremiumAddons\Widgets\Premium_Countdown',
    'premium-counter' => 'PremiumAddons\Widgets\Premium_Counter',
    'premium-dual-header' => 'PremiumAddons\Widgets\Premium_Dual_Header',
    'premium-fancytext' => 'PremiumAddons\Widgets\Premium_Fancytext',
    'premium-grid' => 'PremiumAddons\Widgets\Premium_Grid',
    'premium-icon-list' => 'PremiumAddons\Widgets\Premium_Icon_List',
    'premium-image-button' => 'PremiumAddons\Widgets\Premium_Image_Button',
    'premium-image-scroll' => 'PremiumAddons\Widgets\Premium_Image_Scroll',
    'premium-image-separator' => 'PremiumAddons\Widgets\Premium_Image_Separator',
    'premium-lottie-widget' => 'PremiumAddons\Widgets\Premium_Lottie',
    'premium-maps' => 'PremiumAddons\Widgets\Premium_Maps',
    'premium-media-wheel' => 'PremiumAddons\Widgets\Premium_Media_Wheel',
    'premium-mobile-menu' => 'PremiumAddons\Widgets\Premium_Mobile_Menu',
    'premium-modalbox' => 'PremiumAddons\Widgets\Premium_Modalbox',
    'premium-nav-menu' => 'PremiumAddons\Widgets\Premium_Nav_Menu',
    'premium-notifications' => 'PremiumAddons\Widgets\Premium_Notifications',
    'premium-person' => 'PremiumAddons\Widgets\Premium_Person',
    'premium-pinterest-feed' => 'PremiumAddons\Widgets\Premium_Pinterest_Feed',
    'premium-post-ticker' => 'PremiumAddons\Widgets\Premium_Post_Ticker',
    'premium-pricing-table' => 'PremiumAddons\Widgets\Premium_Pricing_Table',
    'premium-progressbar' => 'PremiumAddons\Widgets\Premium_Progressbar',
    'premium-search-form' => 'PremiumAddons\Widgets\Premium_Search_Form',
    'premium-svg-drawer' => 'PremiumAddons\Widgets\Premium_SVG_Drawer',
    'premium-tcloud' => 'PremiumAddons\Widgets\Premium_Tcloud',
    'premium-testimonials' => 'PremiumAddons\Widgets\Premium_Testimonials',
    'premium-textual-showcase' => 'PremiumAddons\Widgets\Premium_Textual_Showcase',
    'premium-tiktok-feed' => 'PremiumAddons\Widgets\Premium_Tiktok_Feed',
    'premium-title' => 'PremiumAddons\Widgets\Premium_Title',
    'premium-videobox' => 'PremiumAddons\Widgets\Premium_Videobox',
    'premium-vscroll' => 'PremiumAddons\Widgets\Premium_Vscroll',
    'premium-weather' => 'PremiumAddons\Widgets\Premium_Weather',
    'premium-world-clock' => 'PremiumAddons\Widgets\Premium_World_Clock',
);

return $class_map;
