<?php

$names_maps = array(
    'premium-blog' => 'premium-addon-blog',
    'premium-image-hotspots' => 'premium-addon-image-hotspots',
    'premium-image-comparison' => 'premium-addon-image-comparison',
    'premium-content-toggle' => 'premium-addon-content-toggle',
    'premium-magic-section' => 'premium-addon-magic-section',
    'premium-tables' => 'premium-tables-addon',
    'premium-lottie-widget' => 'premium-lottie',
    'premium-carousel' => 'premium-carousel-widget',
    'premium-maps' => 'premium-addon-maps',
    'premium-person' => 'premium-addon-person',
    'premium-tabs' => 'premium-addon-tabs',
    'premium-fancytext' => 'premium-addon-fancy-text',
    'premium-title' => 'premium-addon-title',
    'premium-dual-header' => 'premium-addon-dual-header',
    'premium-grid' => 'premium-img-gallery',
    'premium-countdown' => 'premium-countdown-timer',
    'premium-banner' => 'premium-addon-banner',
    'premium-button' => 'premium-addon-button',
    'premium-image-button' => 'premium-addon-image-button',
    'premium-flipbox' => 'premium-addon-flip-box',
    'premium-iconbox' => 'premium-addon-icon-box',
    'premium-unfold' => 'premium-unfold-addon',
    'premium-img-layers' => 'premium-img-layers-addon',
    'premium-videobox' => 'premium-addon-video-box',
    'premium-modalbox' => 'premium-addon-modal-box',
    'premium-prev-img' => 'premium-addon-preview-image',
    'premium-testimonials' => 'premium-addon-testimonials',
    'premium-progressbar' => 'premium-addon-progressbar',
    'premium-pricing-table' => 'premium-addon-pricing-table',
    'premium-charts' => 'premium-chart',
    'premium-contactform' => 'premium-contact-form',
    'premium-instagram-feed' => 'premium-addon-instagram-feed',
    'premium-behance' => 'premium-behance-feed',
    'premium-image-separator' => 'premium-addon-image-separator',
);

return $names_maps;
